### ISSUE TITLE
Error on recent build

### ISSUE THREAD

**Issue by Sinasta** [brunopostle/homemaker-addon#36]
I am using python 3.10 with blender 3.2 alpha on Archlinux.

When selecting ' Homemaker topologise' on the default Cube i get this error:

Python: Traceback (most recent call last):
  File "/home/sinasta/.config/blender/3.2/scripts/addons/homemaker-addon-main/__init__.py", line 88, in execute
    file = homemaker(
  File "/home/sinasta/.config/blender/3.2/scripts/addons/homemaker-addon-main/__init__.py", line 116, in homemaker
    cc.IndexTopology()
  File "/home/sinasta/.config/blender/3.2/scripts/addons/homemaker-addon-main/topologist/cellcomplex.py", line 14, in IndexTopology
    self.Cells(None, cells_ptr)
TypeError: Cells(): incompatible function arguments. The following argument types are supported:
    1. (self: topologic.CellComplex, rCells: list) -> None

Invoked with: <topologic.CellComplex object at 0x7f900cda1370>, None, []

location: <unknown location>:-1

When selecting ' topologise' on the default Cube i get this error:

Python: Traceback (most recent call last):
  File "/home/sinasta/.config/blender/3.2/scripts/addons/homemaker-addon-main/__init__.py", line 47, in execute
    new_object = bpy.data.objects.new("cellcomplex", mesh_from_cellcomplex(cc))
  File "/home/sinasta/.config/blender/3.2/scripts/addons/homemaker-addon-main/__init__.py", line 178, in mesh_from_cellcomplex
    face_ptr.VerticesPerimeter(vertices_ptr)
  File "/home/sinasta/.config/blender/3.2/scripts/addons/homemaker-addon-main/topologist/face.py", line 58, in VerticesPerimeter
    self.Wires(None, wires_ptr)
TypeError: Wires(): incompatible function arguments. The following argument types are supported:
    1. (self: topologic.Face, rWires: list) -> None

Invoked with: <topologic.Face object at 0x7f900cc32730>, None, []

location: <unknown location>:-1

those errors might be because of the Blender or python version. I just wanted to report this erroe. Thank you a lot for your work!

**Comment by brunopostle** [comment]
Basically, the Topologic API changed because there were performance issues with the old GlobalCluster model.

The good news is that the Homemaker add-on is now several times faster, but you need a current build of Topologic and the Topologic python bindings: https://github.com/wassimj/Topologic

I did a 'release' with a precompiled Topologic last night: https://github.com/brunopostle/homemaker-addon/releases , but this only has python 3.7 and 3.9 bindings, so will only work with the downloads from blender.org and blenderbim.org.

**Comment by Sinasta** [comment]
Thank you for your answer. I rebuild topologic + bindings and everything works perfectly now.
